- name: install apt packages
  become: true
  apt:
    force_apt_get: yes
    name:
      - apt-file
      - libsecret-tools
      - gnome-tweaks
      - chrome-gnome-shell
      - git
      - vim
      - fonts-powerline
      - curl
      - htop
      - tree
      - inotify-tools
      - fswatch
      - xclip
      - jq
      - autojump
      - grip
      - bison
      - binutils
      - build-essential
      - sqsh
      - zip
      - unzip
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - uuid
    cache_valid_time: 3600
    update_cache: true

